### ISSUE TITLE
Variable Italic Marked as Regular [KDE Linux]

### ISSUE THREAD

**Issue by demoy** [Omnibus-Type/Grenze#9]
![Screenshot_20210104_201625](https://user-images.githubusercontent.com/2396524/103596083-14d89d00-4ecb-11eb-85ac-1f44d99d9bda.png)

My guess is flags were copypasted whole from the initial Variable Regular build. The static italic files are identified corrently as italic. Here's some debugging steps I took:

I tried other variable fonts on github: Cabin, Lora, Alegreya, Work Sans, Chivo.
Of these only Chivo's Italic was also marked as Regular.

I tried selecting them in non-kde applications on my linux computer: Firefox and VLC.  In these these the Variable italic appears in place of the true Variable regular font; whilst the true regular font is excluded as a duplicate.

==================================
Unrelated. Grenze Gotisch is so beautiful, it makes me wish english capitalized every noun like german so I can soak up more of the expressiveness. Having the main Grenze font to fall back on for all caps and italic is nice too (which is also how I noticed this issue)

**Comment by Omnibus-Type** [comment]
Hi @demoy many thanks for the report. Try again with these updated files, we change some names on the corresponding tables:

https://github.com/Omnibus-Type/Grenze/tree/master/fonts/gx

If the problem persists, do not hesitate to notify us.

**Comment by demoy** [comment]
Awesome that fixed it. The font size is even smaller now as well. [laugh emoji]
